import React from "react";
export const ThunderBlack = () => {
    return (
      <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="20px" height="21px" viewBox="0 0 20 21" enableBackground="new 0 0 20 21" xmlSpace="preserve">  <image id="image0" width="20" height="21" x="0" y="0"
      href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAVCAMAAABxCz6aAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
  AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAolBMVEVHcEwAAAAAAAAAAAAA
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///+ZupmBAAAANHRSTlMARaK6wQYu2RKj
  7CQc+vk8i1oO8X10BePEXN4U0fApEFv8oGjuj7QDmNAMAucePfY1jVUBds97wAAAAAFiS0dENd62
  2WsAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQflDBwTEQgWAJO8AAAAjElEQVQY02NgwAMY
  TaCACUmQGSrGwooQY4OKsXMgKeSEiHFxI4nx8ILF+PiRrRGAKBREFhMSBouJoLhH1AQBOKFiYuII
  MQmYkyQRYlLSMN0ycDFZObiR8iCgABRTZETzvBJQUBlNTEzFxEQVSyipqaMLaphoaqGLaevo6GKE
  sZ6+AWbAGxphihlLonABnzsZYhwFTuEAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjEtMTItMjhUMTY6
  MTc6MDgrMDM6MDCSqiuWAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIxLTEyLTI4VDE2OjE3OjA4KzAz
  OjAw4/eTKgAAAABJRU5ErkJggg==" />
  </svg>
    );
};

