
  query Product($values: [ID!]) {
    productsByIdentifier(field: id, values: $values) @context(provider: "vtex.search-graphql") {
      productClusters {
        id
      },
      brandId,
      productId
    }
  }

  
  

