query Product($values: [ID!]) {
    productsByIdentifier(field: sku, values: $values)
        @context(provider: "vtex.search-graphql") {
        productClusters {
            id
        }
        brandId
        productId
        categoryTree {
            id
        }
    }
}
